# KELOLA KONEKSI DATABASE H2
spring.datasource.url=jdbc:h2:mem:trashcampdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# AKTIFKAN H2 CONSOLE (UNTUK CEK TABEL DI BROWSER)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# STRATEGI PEMBUATAN TABEL AUTOMATIS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Perbaikan akses H2 Console saat Spring Security aktif nanti
spring.main.allow-bean-definition-overriding=true